---
  name: PART3 - CH1 - Step Output 1
  on: workflow_dispatch
  jobs:
    test-job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - id: generate-random-id
        name: Generate random string
        run: echo "random_id=$RANDOM" >> "$GITHUB_OUTPUT"
      - id: build-project
        name: Build project
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"
      - id: run-tests
        name: Run tests
        run: |
          echo "Random ID: ${{ steps.generate-random-id.outputs.random_id }}"