---
  name: PART3 - CH1 - Variables 3
  on: workflow_dispatch
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build project
        run: |
          echo "Build Project ${{ vars.PROJECT_NAME }}"
      - name: Run tests
        run: |
          echo "Run Test ${{ vars.TEST_ENVIRONMENT }}"
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production server ${{ vars.PRODUCTION_SERVER }}"