---
name: PART3 - CH2 - Trigger when Push all branches except test
on: 
  push:
    branches:
      - '*'
      - '!master'
      - '!test-**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build project
      run: |
        echo "Build Project"
        echo "Branch: $GITHUB_REF"
    - name: Run tests
      run: |
        echo "Run Test"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production server"