---
name: PART3 - CH3 - Self-Hosted Runner
on: 
  workflow_dispatch:
    inputs:
      self-hosted-runner:
        description: 'enter a runner name'
        required: true
        default: 'self-hosted'
jobs:
  build:
    name: Build on self-hosted
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ${{ github.event.inputs.self-hosted-runner }}
    steps:
    - id: checkout
      name: Checkout 
      uses: actions/checkout@v2
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}