---
name: PART3 - CH3 - Multi Matrix Runner
on: workflow_dispatch
jobs:
  build:
    name: Multi OS Build
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - id: checkout
      name: Checkout 
      uses: actions/checkout@v2
    - id: setup-node
      name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}