name: PART4 - CH3 - Large Secret
on: workflow_dispatch
jobs:
  decrypt_large_secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Move Sample code
        run: |
          mv secret_sample/my_secret.json.gpg ./
          mv secret_sample/decrypt_secret.sh ./
      - name: Decrypt Large Secret
        run: |
          chmod +x decrypt_secret.sh
          ./decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE}}
      - name: Show Large Secret
        run: cat $HOME/secrets/my_secret.json
