---
  name: PART3 - CH4 - Google Cloud OIDC
  on: workflow_dispatch
  jobs:
    google-cloud-storage:
      name: Google Cloud Storage Upload using OIDC
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Generate File
        run: |
          echo "Build ID: ${{ github.run_id }}" auth through Google Cloud OIDC > ./build.txt
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }} 
      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ./build.txt
          destination: githubaction-test-01/
          process_gcloudignore: false
      - name: Notice when a build finishes
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{job.status}}
          fields: repo,message,workflow,job,ref
          author_name: Github Action Slack
