name: AWS OIDC Credentials 
on: workflow_dispatch
jobs:
  s3:
    name: S3 Upload using OIDC Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: 깃허브 체크아웃(코드 가져오기)
      uses: actions/checkout@v2

    - name: 업로드 파일 생성
      run: |
        echo "Build ID: ${{ github.run_id }} | auth through AWS OIDC" > ./build.txt

    - name: AWS 인증설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        role-duration-seconds: 900

    - name: AWS S3에 파일 업로드
      run: |
        aws s3 cp build.txt s3://githubaction-test-01/build.txt
