name: PART5 - CH1 - CI (Java with Gradle)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Move Java Sample code
      run: |
        mv build_sample/java/* ./
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: java-build-artifacts
        path: app/build/libs
  s3:
    name: Upload to S3
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: java-build-artifacts
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        role-duration-seconds: 3600
    - name: Upload jar file to S3
      run: |
        aws s3 cp app.jar s3://${{ vars.BUCKET_NAME }}/ 

