name: PART5 - CH1 - CI (Java with Gradle)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: 자바 샘플 코드로 이동
      run: |
        mv build_sample/java/* ./

    - name: 자바설정(17)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle 래퍼 검증
      uses: gradle/wrapper-validation-action@v1

    - name: Gradle 설정
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'

    - name: Gradle 빌드 실행
      run: ./gradlew build

    - name: 빌드 아티팩트 저장 # app/build/libs에 jar 저장
      uses: actions/upload-artifact@v2
      with:
        name: java-build-artifacts
        path: app/build/libs

  s3:
    name: Upload to S3
    needs: build # 선행작업 설정
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: 빌드 아티팩트 다운로드
      uses: actions/download-artifact@v2
      with:
        name: java-build-artifacts

    - name: AWS 증명 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        role-duration-seconds: 3600

    - name: S3에 jar 업로드
      run: |
        aws s3 cp app.jar s3://${{ vars.BUCKET_NAME }}/
