name: PART6 - CH4 - GitHub Packages Build and Push
on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  NAMESPACE: ${{ vars.NAMESPACE }}
  IMAGE_NAME: humancat-server
jobs:
  build:
    name: Humancat Server Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Move Python Sample code
        run: |
          mv build_sample/container_build/* ./
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: GitHub Packages Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
      